---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/EST
    volumes:
      - /etc/sonarr/data:/config
      - /home/ubuntu/Downloads/media/tv:/tv #optional
      - /etc/qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
