---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/EST
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /etc/qbittorrent/appdata:/config
      - /etc/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-2004hubuntu@testing:~/Documents/Compose-Files$ cat radarr/docker-compose.yml 
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/EST
    volumes:
      - /etc/radarr/data:/config
      - /home/ubuntu/Downloads/media/movies:/movies #optional
      - /etc/radarr/download-client-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
